server:
  port: 8084

spring:
    jackson:
        date-format: "yyyy-MM-dd'T'HH:mm:ss"
    data:
        mongodb:
            host: localhost
            port: 27017
            database: real_estate_aggragetor
            auto-index-creation: true