server:
  port: 8085

spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  data:
    mongodb:
      host: rea-offer-db
      port: 27017
      database: real_estate_aggragetor
      auto-index-creation: true